// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  timeout: 30_000,
  retries: 0,
  workers: 1,
  reporter: 'list',
  use: {
    headless: true,
    // Intercept all origins so page.route works for https:// pages too
    ignoreHTTPSErrors: true,
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        // Allow routing https://www.sefaria.org/* requests
        bypassCSP: true,
      },
    },
  ],
});
