# Generated by OrchestKit Claude Plugin
# Created: 2026-02-15

#!/usr/bin/env python3
"""
Load test script for the Sefaria chatbot.

Sends concurrent requests to /api/v2/chat/stream and measures TTFB,
total response time, error rate, and throughput.

Usage:
    # Basic: 50 requests, 10 concurrent
    python -m loadtest.load_test --url http://localhost:8001 -n 50 -c 10

    # Stress test: 200 requests, 50 concurrent
    python -m loadtest.load_test --url http://localhost:8001 -n 200 -c 50

    # With custom messages
    python -m loadtest.load_test --url http://localhost:8001 -n 100 -c 20 \
        --messages "What is Shabbat?" "Explain the Shema" "Who was Rashi?"
"""

from __future__ import annotations

import argparse
import asyncio
import base64
import hashlib
import json
import os
import statistics
import sys
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone

import httpx
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

DEFAULT_MESSAGES = [
    "What is the Shema?",
    "Explain the concept of Shabbat",
    "Who was Maimonides?",
    "What are the 613 mitzvot?",
    "Tell me about the Talmud",
    "What is the significance of Passover?",
    "Explain the concept of tikkun olam",
    "What does the Torah say about justice?",
]


@dataclass
class RequestMetrics:
    ttfb_ms: float = 0
    total_ms: float = 0
    chunks: int = 0
    bytes_received: int = 0
    status_code: int = 0
    error: str | None = None


@dataclass
class LoadTestResults:
    metrics: list[RequestMetrics] = field(default_factory=list)
    start_time: float = 0
    end_time: float = 0

    @property
    def successful(self) -> list[RequestMetrics]:
        return [m for m in self.metrics if not m.error and m.status_code == 200]

    @property
    def failed(self) -> list[RequestMetrics]:
        return [m for m in self.metrics if m.error or m.status_code != 200]

    @property
    def error_rate(self) -> float:
        return len(self.failed) / len(self.metrics) if self.metrics else 0

    @property
    def duration_s(self) -> float:
        return self.end_time - self.start_time

    @property
    def rps(self) -> float:
        return len(self.metrics) / self.duration_s if self.duration_s > 0 else 0

    def percentile(self, values: list[float], p: float) -> float:
        if not values:
            return 0
        sorted_vals = sorted(values)
        k = (len(sorted_vals) - 1) * p / 100
        lo = int(k)
        hi = min(lo + 1, len(sorted_vals) - 1)
        return sorted_vals[lo] + (k - lo) * (sorted_vals[hi] - sorted_vals[lo])

    def summary(self) -> str:
        s = self.successful
        if not s:
            return f"ALL {len(self.metrics)} REQUESTS FAILED"

        ttfbs = [m.ttfb_ms for m in s]
        totals = [m.total_ms for m in s]

        lines = [
            "",
            "=" * 60,
            "LOAD TEST RESULTS",
            "=" * 60,
            f"Total requests:     {len(self.metrics)}",
            f"Successful:         {len(s)}",
            f"Failed:             {len(self.failed)}",
            f"Error rate:         {self.error_rate:.1%}",
            f"Duration:           {self.duration_s:.1f}s",
            f"Requests/sec:       {self.rps:.1f}",
            "",
            "--- Time to First Byte (TTFB) ---",
            f"  Min:              {min(ttfbs):.0f}ms",
            f"  Median (p50):     {self.percentile(ttfbs, 50):.0f}ms",
            f"  p90:              {self.percentile(ttfbs, 90):.0f}ms",
            f"  p95:              {self.percentile(ttfbs, 95):.0f}ms",
            f"  p99:              {self.percentile(ttfbs, 99):.0f}ms",
            f"  Max:              {max(ttfbs):.0f}ms",
            "",
            "--- Total Response Time ---",
            f"  Min:              {min(totals):.0f}ms",
            f"  Median (p50):     {self.percentile(totals, 50):.0f}ms",
            f"  p90:              {self.percentile(totals, 90):.0f}ms",
            f"  p95:              {self.percentile(totals, 95):.0f}ms",
            f"  p99:              {self.percentile(totals, 99):.0f}ms",
            f"  Max:              {max(totals):.0f}ms",
            "=" * 60,
        ]

        if self.failed:
            error_counts: dict[str, int] = {}
            for m in self.failed:
                key = m.error or f"HTTP {m.status_code}"
                error_counts[key] = error_counts.get(key, 0) + 1
            lines.append("")
            lines.append("--- Errors ---")
            for err, count in sorted(error_counts.items(), key=lambda x: -x[1]):
                lines.append(f"  {err}: {count}")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Auth helper
# ---------------------------------------------------------------------------


def _create_test_token(user_id: str, secret: str = "secret") -> str:
    """Create a valid encrypted userId token for load testing."""
    expires_at = datetime.now(timezone.utc) + timedelta(hours=1)
    payload = {"id": user_id, "expiration": expires_at.isoformat()}
    payload_bytes = json.dumps(payload).encode("utf-8")
    key = hashlib.sha256(secret.encode("utf-8")).digest()
    aesgcm = AESGCM(key)
    nonce = b"\x00" * 12
    encrypted = aesgcm.encrypt(nonce, payload_bytes, None)
    token_bytes = nonce + encrypted
    return base64.urlsafe_b64encode(token_bytes).decode("ascii").rstrip("=")


def _make_user_token() -> str:
    """Create a valid encrypted userId token for load testing."""
    secret = os.environ.get("CHATBOT_USER_TOKEN_SECRET", "secret")
    user_id = f"loadtest-user-{uuid.uuid4().hex[:8]}"
    return _create_test_token(user_id, secret)


# ---------------------------------------------------------------------------
# Single request
# ---------------------------------------------------------------------------


async def send_chat_request(
    client: httpx.AsyncClient,
    base_url: str,
    message: str,
    semaphore: asyncio.Semaphore,
    user_token: str | None = None,
) -> RequestMetrics:
    metrics = RequestMetrics()
    start = time.perf_counter()
    token = user_token or _make_user_token()

    payload = {
        "userId": token,
        "sessionId": str(uuid.uuid4()),
        "messageId": str(uuid.uuid4()),
        "text": message,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    try:
        async with semaphore:
            async with client.stream(
                "POST",
                f"{base_url}/api/v2/chat/stream",
                json=payload,
                timeout=120.0,
            ) as response:
                metrics.status_code = response.status_code

                if response.status_code != 200:
                    body = await response.aread()
                    metrics.error = f"HTTP {response.status_code}: {body[:200].decode()}"
                    metrics.total_ms = (time.perf_counter() - start) * 1000
                    return metrics

                async for chunk in response.aiter_bytes():
                    if metrics.chunks == 0:
                        metrics.ttfb_ms = (time.perf_counter() - start) * 1000
                    metrics.chunks += 1
                    metrics.bytes_received += len(chunk)

        metrics.total_ms = (time.perf_counter() - start) * 1000
    except httpx.TimeoutException:
        metrics.error = "Timeout (120s)"
        metrics.total_ms = (time.perf_counter() - start) * 1000
    except httpx.ConnectError as e:
        metrics.error = f"Connection error: {e}"
        metrics.total_ms = (time.perf_counter() - start) * 1000
    except Exception as e:
        metrics.error = f"{type(e).__name__}: {e}"
        metrics.total_ms = (time.perf_counter() - start) * 1000

    return metrics


# ---------------------------------------------------------------------------
# Main runner
# ---------------------------------------------------------------------------


async def run_load_test(
    base_url: str,
    num_requests: int = 50,
    concurrency: int = 10,
    messages: list[str] | None = None,
    user_token: str | None = None,
    ramp_up_seconds: float = 0,
) -> LoadTestResults:
    messages = messages or DEFAULT_MESSAGES
    # Per-request token = new user + new session per request (mimics real load)
    use_shared_token = user_token is not None
    semaphore = asyncio.Semaphore(concurrency)
    results = LoadTestResults()

    print(f"Starting load test: {num_requests} requests, {concurrency} concurrent")
    print(f"Target: {base_url}/api/v2/chat/stream")
    print(f"Mode: {'shared user' if use_shared_token else 'new user+session per request'}")
    print()

    async with httpx.AsyncClient() as client:
        tasks = []
        results.start_time = time.perf_counter()

        for i in range(num_requests):
            msg = messages[i % len(messages)]
            task = asyncio.create_task(
                send_chat_request(client, base_url, msg, semaphore, user_token)
            )
            tasks.append(task)

            # Optional ramp-up: stagger task start times
            if ramp_up_seconds > 0 and i < num_requests - 1:
                await asyncio.sleep(ramp_up_seconds / num_requests)

        results.metrics = await asyncio.gather(*tasks)
        results.end_time = time.perf_counter()

    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="Load test the Sefaria chatbot")
    parser.add_argument(
        "--url",
        default="http://localhost:8001",
        help="Base URL of the chatbot server (default: http://localhost:8001)",
    )
    parser.add_argument(
        "-n",
        "--num-requests",
        type=int,
        default=50,
        help="Total number of requests to send (default: 50)",
    )
    parser.add_argument(
        "-c",
        "--concurrency",
        type=int,
        default=10,
        help="Max concurrent requests (default: 10)",
    )
    parser.add_argument(
        "--messages",
        nargs="+",
        help="Custom messages to send (cycles through them)",
    )
    parser.add_argument(
        "--user-token",
        help="User token for authentication (default: auto-generated)",
    )
    parser.add_argument(
        "--ramp-up",
        type=float,
        default=0,
        help="Ramp-up period in seconds (default: 0, all at once)",
    )
    parser.add_argument(
        "--json-output",
        help="Write results to JSON file",
    )

    args = parser.parse_args()

    results = asyncio.run(
        run_load_test(
            base_url=args.url,
            num_requests=args.num_requests,
            concurrency=args.concurrency,
            messages=args.messages,
            user_token=args.user_token,
            ramp_up_seconds=args.ramp_up,
        )
    )

    print(results.summary())

    if args.json_output:
        output = {
            "total_requests": len(results.metrics),
            "successful": len(results.successful),
            "failed": len(results.failed),
            "error_rate": results.error_rate,
            "duration_s": results.duration_s,
            "rps": results.rps,
            "ttfb": {
                "p50": results.percentile([m.ttfb_ms for m in results.successful], 50),
                "p95": results.percentile([m.ttfb_ms for m in results.successful], 95),
                "p99": results.percentile([m.ttfb_ms for m in results.successful], 99),
            },
            "total_time": {
                "p50": results.percentile(
                    [m.total_ms for m in results.successful], 50
                ),
                "p95": results.percentile(
                    [m.total_ms for m in results.successful], 95
                ),
                "p99": results.percentile(
                    [m.total_ms for m in results.successful], 99
                ),
            },
            "errors": [
                {"error": m.error, "status_code": m.status_code} for m in results.failed
            ],
        }
        with open(args.json_output, "w") as f:
            json.dump(output, f, indent=2)
        print(f"\nResults written to {args.json_output}")


if __name__ == "__main__":
    main()
