# Generated by OrchestKit Claude Plugin
# Created: 2026-02-15

"""
Mock Anthropic API server for load testing.

Mimics the Anthropic Messages API streaming format so the Claude Agent SDK
runs its full tool-calling loop without hitting the real API. This lets us
measure Django server capacity (threads, memory, DB connections) at zero cost.

Usage:
    uvicorn loadtest.mock_anthropic:app --port 8002

Then point the chatbot server at it:
    ANTHROPIC_BASE_URL=http://localhost:8002 python manage.py runserver 0.0.0.0:8001
"""

from __future__ import annotations

import asyncio
import json
import random
import time
import uuid
from dataclasses import dataclass, field

from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse

app = FastAPI(title="Mock Anthropic API")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Sefaria tool names the agent's MCP server registers (prefixed mcp__sefaria__).
# The mock picks from these to simulate realistic tool-calling behaviour.
SEFARIA_TOOLS = [
    ("get_text", {"reference": "Genesis 1:1"}),
    ("get_text", {"reference": "Berakhot 2a"}),
    ("text_search", {"query": "shabbat"}),
    ("get_topic_details", {"topic_slug": "shabbat"}),
    ("english_semantic_search", {"query": "what is the meaning of life"}),
    ("get_links_between_texts", {"reference": "Genesis 1:1"}),
    ("search_in_book", {"query": "prayer", "book_name": "Berakhot"}),
    ("get_current_calendar", {}),
]

# Canned response fragments the mock streams token-by-token.
RESPONSE_FRAGMENTS = [
    "Based on the sources I found, ",
    "this is a fascinating topic in Jewish tradition. ",
    "The text discusses the fundamental principles ",
    "that have guided Jewish thought for centuries. ",
    "According to the commentaries, ",
    "there are several important perspectives to consider. ",
    "The Talmud provides additional context, ",
    "highlighting the depth of this teaching. ",
    "Many scholars have noted the significance ",
    "of this passage in understanding Jewish law and ethics.",
]


@dataclass
class MockConfig:
    """Tuneable parameters for the mock server."""

    # How many tool calls to simulate per conversation turn (0 = text-only response)
    tool_calls_per_turn: int = 2
    # Seconds between streamed tokens (target ~5-15s total flow; ~0.1 gives ~8-10s)
    token_delay: float = 0.10
    # Random jitter added to token_delay (± this value)
    token_jitter: float = 0.05
    # How many response fragments to include in the final answer
    response_fragments: int = 6
    # Simulated input token count
    input_tokens: int = 3500
    # Whether to simulate guardrail calls (model=haiku → fast short response)
    simulate_guardrail: bool = True


CONFIG = MockConfig()


# ---------------------------------------------------------------------------
# SSE helpers — exact Anthropic wire format
# ---------------------------------------------------------------------------


def _msg_id() -> str:
    return f"msg_{uuid.uuid4().hex[:24]}"


def _tool_use_id() -> str:
    return f"toolu_{uuid.uuid4().hex[:24]}"


def _sse(event: str, data: dict) -> str:
    """Format a single SSE event line."""
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


# ---------------------------------------------------------------------------
# Stream generators
# ---------------------------------------------------------------------------


def _build_text_token_events(text: str, index: int) -> list[str]:
    """Split text into word-level tokens and return content_block_delta events."""
    events: list[str] = []
    words = text.split(" ")
    for i, word in enumerate(words):
        token = word if i == 0 else f" {word}"
        events.append(
            _sse(
                "content_block_delta",
                {
                    "type": "content_block_delta",
                    "index": index,
                    "delta": {"type": "text_delta", "text": token},
                },
            )
        )
    return events


def _build_tool_use_events(
    index: int, tool_name: str, tool_input: dict
) -> list[str]:
    """Build the SSE events for a tool_use content block."""
    tool_id = _tool_use_id()
    events = []

    # content_block_start
    events.append(
        _sse(
            "content_block_start",
            {
                "type": "content_block_start",
                "index": index,
                "content_block": {
                    "type": "tool_use",
                    "id": tool_id,
                    "name": tool_name,
                    "input": {},
                },
            },
        )
    )

    # Stream the input JSON in chunks (mimics real API behaviour)
    input_json = json.dumps(tool_input)
    chunk_size = 12
    for i in range(0, len(input_json), chunk_size):
        events.append(
            _sse(
                "content_block_delta",
                {
                    "type": "content_block_delta",
                    "index": index,
                    "delta": {
                        "type": "input_json_delta",
                        "partial_json": input_json[i : i + chunk_size],
                    },
                },
            )
        )

    # content_block_stop
    events.append(
        _sse("content_block_stop", {"type": "content_block_stop", "index": index})
    )

    return events


def _has_tool_results(messages: list[dict]) -> bool:
    """Check if the conversation already contains tool_result messages."""
    for msg in messages:
        if msg.get("role") == "user":
            content = msg.get("content", [])
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "tool_result":
                        return True
    return False


def _count_tool_result_rounds(messages: list[dict]) -> int:
    """Count how many tool_result round-trips have occurred.

    Counts distinct user messages containing at least one tool_result block,
    not individual blocks (a single round may include parallel tool results).
    """
    count = 0
    for msg in messages:
        if msg.get("role") == "user":
            content = msg.get("content", [])
            if isinstance(content, list) and any(
                isinstance(b, dict) and b.get("type") == "tool_result"
                for b in content
            ):
                count += 1
    return count


def _is_guardrail_request(request_body: dict) -> bool:
    """Detect guardrail/classification requests (short, uses haiku model)."""
    model = request_body.get("model", "")
    return "haiku" in model


async def _generate_stream(request_body: dict):
    """Main SSE generator — produces the full event stream for one API call."""
    model = request_body.get("model", "claude-sonnet-4-5-20250929")
    messages = request_body.get("messages", [])
    tools = request_body.get("tools", [])
    max_tokens = request_body.get("max_tokens", 4096)

    msg_id = _msg_id()
    output_tokens = 0
    delay = CONFIG.token_delay
    jitter = CONFIG.token_jitter

    # --- Guardrail requests get a fast, short response ---
    if _is_guardrail_request(request_body):
        yield _sse(
            "message_start",
            {
                "type": "message_start",
                "message": {
                    "id": msg_id,
                    "type": "message",
                    "role": "assistant",
                    "content": [],
                    "model": model,
                    "stop_reason": None,
                    "stop_sequence": None,
                    "usage": {"input_tokens": 200, "output_tokens": 1},
                },
            },
        )
        # Single text block: "allowed"
        yield _sse(
            "content_block_start",
            {
                "type": "content_block_start",
                "index": 0,
                "content_block": {"type": "text", "text": ""},
            },
        )
        yield _sse(
            "content_block_delta",
            {
                "type": "content_block_delta",
                "index": 0,
                "delta": {"type": "text_delta", "text": '{"allowed": true}'},
            },
        )
        yield _sse(
            "content_block_stop", {"type": "content_block_stop", "index": 0}
        )
        yield _sse(
            "message_delta",
            {
                "type": "message_delta",
                "delta": {"stop_reason": "end_turn", "stop_sequence": None},
                "usage": {"output_tokens": 10},
            },
        )
        yield _sse("message_stop", {"type": "message_stop"})
        return

    # --- Determine whether to return tool_use or final text ---
    tool_rounds_done = _count_tool_result_rounds(messages)
    should_call_tools = (
        tools
        and tool_rounds_done < CONFIG.tool_calls_per_turn
    )

    # message_start
    yield _sse(
        "message_start",
        {
            "type": "message_start",
            "message": {
                "id": msg_id,
                "type": "message",
                "role": "assistant",
                "content": [],
                "model": model,
                "stop_reason": None,
                "stop_sequence": None,
                "usage": {"input_tokens": CONFIG.input_tokens, "output_tokens": 1},
            },
        },
    )

    yield _sse("ping", {"type": "ping"})

    block_index = 0

    if should_call_tools:
        # --- Stream a brief preamble text, then a tool_use block ---
        preamble = "Let me look that up for you."
        yield _sse(
            "content_block_start",
            {
                "type": "content_block_start",
                "index": block_index,
                "content_block": {"type": "text", "text": ""},
            },
        )
        for event in _build_text_token_events(preamble, block_index):
            yield event
            await asyncio.sleep(delay + random.uniform(-jitter, jitter))
        yield _sse(
            "content_block_stop",
            {"type": "content_block_stop", "index": block_index},
        )
        block_index += 1
        output_tokens += len(preamble.split())

        # Pick a random tool to call
        tool_name, tool_input = random.choice(SEFARIA_TOOLS)
        # Use the MCP-prefixed name that the SDK expects
        prefixed_name = f"mcp__sefaria__{tool_name}"

        for event in _build_tool_use_events(block_index, prefixed_name, tool_input):
            yield event
            await asyncio.sleep(delay)
        block_index += 1
        output_tokens += 20

        stop_reason = "tool_use"
    else:
        # --- Stream the final text response ---
        fragments = random.sample(
            RESPONSE_FRAGMENTS,
            min(CONFIG.response_fragments, len(RESPONSE_FRAGMENTS)),
        )
        full_text = "".join(fragments)

        yield _sse(
            "content_block_start",
            {
                "type": "content_block_start",
                "index": block_index,
                "content_block": {"type": "text", "text": ""},
            },
        )

        for event in _build_text_token_events(full_text, block_index):
            yield event
            await asyncio.sleep(delay + random.uniform(-jitter, jitter))

        yield _sse(
            "content_block_stop",
            {"type": "content_block_stop", "index": block_index},
        )
        output_tokens += len(full_text.split())
        stop_reason = "end_turn"

    # message_delta (usage is cumulative)
    yield _sse(
        "message_delta",
        {
            "type": "message_delta",
            "delta": {"stop_reason": stop_reason, "stop_sequence": None},
            "usage": {"output_tokens": output_tokens},
        },
    )

    # message_stop
    yield _sse("message_stop", {"type": "message_stop"})


# ---------------------------------------------------------------------------
# API endpoint
# ---------------------------------------------------------------------------


@app.post("/v1/messages")
async def messages(request: Request):
    """Drop-in replacement for POST https://api.anthropic.com/v1/messages."""
    body = await request.json()

    # Non-streaming: return a simple complete response
    if not body.get("stream", False):
        # Guardrail expects {decision: "ALLOW", reason: "..."}; main agent uses streaming
        model = body.get("model", "claude-sonnet-4-5-20250929")
        text = (
            '{"decision": "ALLOW", "reason": ""}'
            if "haiku" in model
            else '{"allowed": true}'
        )
        return {
            "id": _msg_id(),
            "type": "message",
            "role": "assistant",
            "content": [{"type": "text", "text": text}],
            "model": model,
            "stop_reason": "end_turn",
            "stop_sequence": None,
            "usage": {"input_tokens": 200, "output_tokens": 10},
        }

    return StreamingResponse(
        _generate_stream(body),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@app.get("/v1/models")
async def list_models():
    """Minimal models endpoint for SDK compatibility."""
    return {
        "data": [
            {"id": "claude-sonnet-4-5-20250929", "object": "model"},
            {"id": "claude-3-5-haiku-20241022", "object": "model"},
        ]
    }


@app.get("/health")
async def health():
    return {"status": "ok", "type": "mock-anthropic"}


@app.post("/v1/messages/count_tokens")
async def count_tokens(request: Request):
    """Mock token counting endpoint."""
    return {"input_tokens": CONFIG.input_tokens}


# ---------------------------------------------------------------------------
# Config endpoint — adjust mock behaviour at runtime
# ---------------------------------------------------------------------------


@app.get("/config")
async def get_config():
    return {
        "tool_calls_per_turn": CONFIG.tool_calls_per_turn,
        "token_delay": CONFIG.token_delay,
        "token_jitter": CONFIG.token_jitter,
        "response_fragments": CONFIG.response_fragments,
        "input_tokens": CONFIG.input_tokens,
    }


@app.put("/config")
async def update_config(request: Request):
    """Update mock config at runtime (useful during load test runs)."""
    body = await request.json()
    for key, value in body.items():
        if hasattr(CONFIG, key):
            setattr(CONFIG, key, value)
    return await get_config()
