# Generated by OrchestKit Claude Plugin
# Created: 2026-02-15

"""Tests for the mock Anthropic API server."""

from __future__ import annotations

import json

import pytest
from httpx import ASGITransport, AsyncClient

from .mock_anthropic import CONFIG, app


@pytest.fixture(autouse=True)
def reset_config():
    """Reset mock config between tests."""
    original = {
        "tool_calls_per_turn": CONFIG.tool_calls_per_turn,
        "token_delay": CONFIG.token_delay,
        "token_jitter": CONFIG.token_jitter,
        "response_fragments": CONFIG.response_fragments,
        "input_tokens": CONFIG.input_tokens,
    }
    # Speed up tests
    CONFIG.token_delay = 0
    CONFIG.token_jitter = 0
    yield
    for key, value in original.items():
        setattr(CONFIG, key, value)


@pytest.fixture
async def client():
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        yield c


@pytest.mark.asyncio
async def test_health(client):
    resp = await client.get("/health")
    assert resp.status_code == 200
    assert resp.json()["status"] == "ok"


@pytest.mark.asyncio
async def test_non_streaming_response(client):
    """Non-streaming request returns a complete JSON response."""
    resp = await client.post(
        "/v1/messages",
        json={
            "model": "claude-sonnet-4-5-20250929",
            "messages": [{"role": "user", "content": "Hello"}],
            "max_tokens": 100,
            "stream": False,
        },
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["type"] == "message"
    assert data["role"] == "assistant"
    assert len(data["content"]) > 0


@pytest.mark.asyncio
async def test_streaming_text_response(client):
    """Streaming request with no tools returns text-only SSE events."""
    CONFIG.tool_calls_per_turn = 0

    resp = await client.post(
        "/v1/messages",
        json={
            "model": "claude-sonnet-4-5-20250929",
            "messages": [{"role": "user", "content": "Hello"}],
            "max_tokens": 100,
            "stream": True,
        },
    )
    assert resp.status_code == 200

    events = _parse_sse(resp.text)

    # Check event flow: message_start → content_block_start → deltas → stop → message_delta → message_stop
    event_types = [e["type"] for e in events if e.get("type") != "ping"]
    assert event_types[0] == "message_start"
    assert "content_block_start" in event_types
    assert "content_block_delta" in event_types
    assert "content_block_stop" in event_types
    assert event_types[-2] == "message_delta"
    assert event_types[-1] == "message_stop"

    # Check stop_reason is end_turn
    message_delta = next(e for e in events if e.get("type") == "message_delta")
    assert message_delta["delta"]["stop_reason"] == "end_turn"


@pytest.mark.asyncio
async def test_streaming_tool_use_response(client):
    """First request with tools triggers a tool_use response."""
    CONFIG.tool_calls_per_turn = 1

    resp = await client.post(
        "/v1/messages",
        json={
            "model": "claude-sonnet-4-5-20250929",
            "messages": [{"role": "user", "content": "What is Genesis 1:1?"}],
            "max_tokens": 1000,
            "stream": True,
            "tools": [{"name": "mcp__sefaria__get_text", "description": "Get text"}],
        },
    )
    assert resp.status_code == 200

    events = _parse_sse(resp.text)

    # Should have a tool_use content block
    tool_blocks = [
        e
        for e in events
        if e.get("type") == "content_block_start"
        and e.get("content_block", {}).get("type") == "tool_use"
    ]
    assert len(tool_blocks) == 1

    # Should have input_json_delta events
    json_deltas = [
        e
        for e in events
        if e.get("type") == "content_block_delta"
        and e.get("delta", {}).get("type") == "input_json_delta"
    ]
    assert len(json_deltas) > 0

    # Accumulated JSON should be valid
    partial_json = "".join(d["delta"]["partial_json"] for d in json_deltas)
    parsed = json.loads(partial_json)
    assert isinstance(parsed, dict)

    # Stop reason should be tool_use
    message_delta = next(e for e in events if e.get("type") == "message_delta")
    assert message_delta["delta"]["stop_reason"] == "tool_use"


@pytest.mark.asyncio
async def test_tool_result_triggers_text_response(client):
    """After tool_result, mock returns final text (not more tools)."""
    CONFIG.tool_calls_per_turn = 1

    resp = await client.post(
        "/v1/messages",
        json={
            "model": "claude-sonnet-4-5-20250929",
            "messages": [
                {"role": "user", "content": "What is Genesis 1:1?"},
                {
                    "role": "assistant",
                    "content": [
                        {"type": "text", "text": "Let me look that up."},
                        {
                            "type": "tool_use",
                            "id": "toolu_test123",
                            "name": "mcp__sefaria__get_text",
                            "input": {"reference": "Genesis 1:1"},
                        },
                    ],
                },
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "tool_result",
                            "tool_use_id": "toolu_test123",
                            "content": "In the beginning God created...",
                        }
                    ],
                },
            ],
            "max_tokens": 1000,
            "stream": True,
            "tools": [{"name": "mcp__sefaria__get_text", "description": "Get text"}],
        },
    )
    assert resp.status_code == 200

    events = _parse_sse(resp.text)

    # Should NOT have tool_use blocks (already did 1 round, limit is 1)
    tool_blocks = [
        e
        for e in events
        if e.get("type") == "content_block_start"
        and e.get("content_block", {}).get("type") == "tool_use"
    ]
    assert len(tool_blocks) == 0

    # Should have text deltas
    text_deltas = [
        e
        for e in events
        if e.get("type") == "content_block_delta"
        and e.get("delta", {}).get("type") == "text_delta"
    ]
    assert len(text_deltas) > 0

    # Stop reason should be end_turn
    message_delta = next(e for e in events if e.get("type") == "message_delta")
    assert message_delta["delta"]["stop_reason"] == "end_turn"


@pytest.mark.asyncio
async def test_guardrail_request(client):
    """Haiku model requests get fast guardrail-style responses."""
    resp = await client.post(
        "/v1/messages",
        json={
            "model": "claude-3-5-haiku-20241022",
            "messages": [{"role": "user", "content": "Is this allowed?"}],
            "max_tokens": 100,
            "stream": True,
        },
    )
    assert resp.status_code == 200

    events = _parse_sse(resp.text)
    text_deltas = [
        e
        for e in events
        if e.get("type") == "content_block_delta"
        and e.get("delta", {}).get("type") == "text_delta"
    ]
    full_text = "".join(d["delta"]["text"] for d in text_deltas)
    assert "allowed" in full_text


@pytest.mark.asyncio
async def test_config_endpoint(client):
    """Config can be read and updated at runtime."""
    resp = await client.get("/config")
    assert resp.status_code == 200
    config = resp.json()
    assert "tool_calls_per_turn" in config

    resp = await client.put("/config", json={"tool_calls_per_turn": 5})
    assert resp.status_code == 200
    assert resp.json()["tool_calls_per_turn"] == 5


@pytest.mark.asyncio
async def test_multiple_tool_rounds(client):
    """Mock supports configurable number of tool-calling rounds."""
    CONFIG.tool_calls_per_turn = 2
    tools = [{"name": "mcp__sefaria__get_text", "description": "Get text"}]

    def _stop_reason(resp_text: str) -> str:
        events = _parse_sse(resp_text)
        md = next(e for e in events if e.get("type") == "message_delta")
        return md["delta"]["stop_reason"]

    # Round 0: no tool results yet → should return tool_use
    resp = await client.post(
        "/v1/messages",
        json={
            "model": "claude-sonnet-4-5-20250929",
            "messages": [{"role": "user", "content": "Research this topic"}],
            "max_tokens": 1000,
            "stream": True,
            "tools": tools,
        },
    )
    assert _stop_reason(resp.text) == "tool_use"

    # Round 1: 1 tool result → still should return tool_use (need 2 total)
    resp = await client.post(
        "/v1/messages",
        json={
            "model": "claude-sonnet-4-5-20250929",
            "messages": [
                {"role": "user", "content": "Research this topic"},
                {
                    "role": "assistant",
                    "content": [
                        {"type": "tool_use", "id": "t1", "name": "get_text", "input": {}},
                    ],
                },
                {
                    "role": "user",
                    "content": [{"type": "tool_result", "tool_use_id": "t1", "content": "..."}],
                },
            ],
            "max_tokens": 1000,
            "stream": True,
            "tools": tools,
        },
    )
    assert _stop_reason(resp.text) == "tool_use"

    # Round 2: 2 tool results → should return end_turn (limit reached)
    resp = await client.post(
        "/v1/messages",
        json={
            "model": "claude-sonnet-4-5-20250929",
            "messages": [
                {"role": "user", "content": "Research this topic"},
                {
                    "role": "assistant",
                    "content": [
                        {"type": "tool_use", "id": "t1", "name": "get_text", "input": {}},
                    ],
                },
                {
                    "role": "user",
                    "content": [{"type": "tool_result", "tool_use_id": "t1", "content": "..."}],
                },
                {
                    "role": "assistant",
                    "content": [
                        {"type": "tool_use", "id": "t2", "name": "get_text", "input": {}},
                    ],
                },
                {
                    "role": "user",
                    "content": [{"type": "tool_result", "tool_use_id": "t2", "content": "..."}],
                },
            ],
            "max_tokens": 1000,
            "stream": True,
            "tools": tools,
        },
    )
    assert _stop_reason(resp.text) == "end_turn"


# ---------------------------------------------------------------------------
# SSE parser helper
# ---------------------------------------------------------------------------


def _parse_sse(text: str) -> list[dict]:
    """Parse SSE text into a list of data dicts."""
    events = []
    for line in text.strip().split("\n"):
        if line.startswith("data: "):
            events.append(json.loads(line[6:]))  # Let JSONDecodeError propagate
    return events
