// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

/**
 * Shared test helpers for the lc-chatbot e2e suite.
 *
 * All three tests use a sefaria.org-origin fixture so:
 *   - The location-pin hostname check passes (test 2)
 *   - The appetizer click dispatches sefaria:bootstrap-url in-page (test 3)
 *   - The trail ref link test also works on the same origin (test 1)
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BUNDLE_PATH = join(__dirname, '../dist/lc-chatbot.js');

/** HTML fixture served at https://www.sefaria.org/Genesis.1.1 */
function buildFixtureHtml(apiBase = 'https://www.sefaria.org/api') {
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Genesis 1:1 - Sefaria</title></head>
<body>
  <lc-chatbot
    user-id="test-user"
    api-base-url="${apiBase}"
    default-open="true"
    interface-lang="en"
  ></lc-chatbot>
  <script type="module" src="https://www.sefaria.org/__lc_bundle.js"></script>
</body>
</html>`;
}

/**
 * Build the SSE body for the mocked /chat/stream endpoint.
 * Includes: appetizer, status, tool_start, tool_end, message.
 * - `markdown`: final answer text (pass a long string to force a tall response
 *   package for scroll-positioning tests).
 * - `omitRefData`: emit the tool_start WITHOUT backend refData, to exercise the
 *   client-side trail-link fallback (the ref-API-replacement fallback).
 */
function buildSseBody({ markdown = 'Here is **Genesis 1:1**.', omitRefData = false } = {}) {
  const messageData = JSON.stringify({
    messageId: 'm1', sessionId: 's1', timestamp: '2026-06-22T00:00:00Z',
    markdown, traceId: 't1', toolCalls: [], stats: {}, session: {},
  });
  const toolStart = omitRefData
    ? '{"type":"tool_start","toolName":"get_text","description":"Fetching text \\"Genesis 1:1\\"","toolInput":{"reference":"Genesis 1:1"}}'
    : '{"type":"tool_start","toolName":"get_text","description":"Fetching text \\"Genesis 1:1\\"","toolInput":{"reference":"Genesis 1:1"},"refData":{"is_ref":true,"url_ref":"Genesis.1.1","en":"Genesis 1:1","he":"\\u05d1\\u05e8\\u05d0\\u05e9\\u05d9\\u05ea \\u05d0\\u05f3:\\u05d0\\u05f3"}}';
  return [
    'event: progress',
    'data: {"type":"appetizer","appetizerData":{"topics":[{"topicSlug":"shabbat","topicTitle":"Shabbat","topicUrl":"https://www.sefaria.org/topics/shabbat"}]}}',
    '',
    'event: progress',
    'data: {"type":"status","text":"Thinking\\u2026"}',
    '',
    'event: progress',
    `data: ${toolStart}`,
    '',
    'event: progress',
    'data: {"type":"tool_end","toolName":"get_text","isError":false}',
    '',
    'event: message',
    `data: ${messageData}`,
    '',
    '',
  ].join('\n');
}

/**
 * Register all route mocks for the widget on the given page.
 * apiBase should match the api-base-url attribute (e.g. "https://www.sefaria.org/api").
 * For the location-pin test, mock404Ref=true makes /api/ref/** return 404.
 */
export async function setupMocks(page, { mock404Ref = false, markdown, omitRefData = false } = {}) {
  // Prompt defaults
  await page.route('**/v2/prompts/defaults', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ corePromptSlug: 'test', labs: false }) })
  );

  // History
  await page.route('**/history**', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ messages: [], hasMore: false, session: null }) })
  );

  // Telemetry
  await page.route('**/v2/chat/client-event', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '{}' })
  );

  // Recovery
  await page.route('**/v2/chat/recover', (route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: '{}' })
  );

  // SSE stream
  const sseBody = buildSseBody({ markdown, omitRefData });
  await page.route('**/chat/stream', (route) =>
    route.fulfill({
      status: 200,
      headers: { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' },
      body: sseBody,
    })
  );

  // Sefaria /api/ref — 404 when requested (forces tref fallback for location pin)
  if (mock404Ref) {
    await page.route('https://www.sefaria.org/api/ref/**', (route) =>
      route.fulfill({ status: 404, body: 'Not Found' })
    );
  }
}

/**
 * Set up the sefaria.org-origin fixture:
 *   - Routes https://www.sefaria.org/Genesis.1.1 → HTML fixture
 *   - Routes https://www.sefaria.org/__lc_bundle.js → dist/lc-chatbot.js
 */
export async function setupSefariaOriginFixture(page) {
  const bundleSource = readFileSync(BUNDLE_PATH, 'utf8');

  await page.route('https://www.sefaria.org/Genesis.1.1', (route) =>
    route.fulfill({
      status: 200,
      contentType: 'text/html',
      body: buildFixtureHtml('https://www.sefaria.org/api'),
    })
  );

  await page.route('https://www.sefaria.org/__lc_bundle.js', (route) =>
    route.fulfill({
      status: 200,
      contentType: 'application/javascript',
      body: bundleSource,
    })
  );
}

/**
 * Wait for the widget panel to be open and ready.
 * With default-open="true" this usually just needs a tick, but we wait for
 * the textarea to appear to confirm the panel is fully rendered.
 */
export async function waitForPanelReady(page) {
  await page.waitForSelector('textarea', { timeout: 10_000 });
}

/**
 * Type text into the widget's textarea and click Send.
 */
export async function sendMessage(page, text) {
  const textarea = page.locator('textarea');
  await textarea.fill(text);
  const sendBtn = page.locator('button.send-btn');
  await sendBtn.click();
}
