// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

/**
 * Test 2 — Location pin (tref fallback when /api/ref 404s)
 *
 * On a sefaria.org page at path "Genesis.1.1":
 *   - window.location.hostname = "www.sefaria.org" → isSefariaHostname passes
 *   - extractCandidateTref returns "Genesis.1.1"
 *   - fetchRefData returns null (mocked 404)
 *   - refToUrlPath("Genesis.1.1") → "Genesis.1.1" (already dotted)
 *     Wait: refToUrlPath expects "Genesis 1:1" format with space.
 *     For a path like "Genesis.1.1" refToUrlPath returns null (no space match).
 *     BUT refLabelFromTref("Genesis.1.1") → "Genesis 1:1" label.
 *     AND the fallback url = "https://www.sefaria.org/Genesis.1.1"
 *
 * Actually looking at the code:
 *   refToUrlPath(ref) tries to match /^(.+?)[\s.](\d[\w:.\-–]*)$/ on "Genesis.1.1"
 *   That matches: m[1]="Genesis", m[2]="1.1" → returns "Genesis.1.1"
 *   So fallback IS returned.
 *
 * The user message gets a locationRef = { label: "Genesis 1:1", url: "https://www.sefaria.org/Genesis.1.1" }
 * and LocationTag renders: <a class="lc-location-tag" href="..."><span class="lc-location-ref">Genesis 1:1</span></a>
 *
 * This test verifies the location tag appears with correct label and href.
 */

import { test, expect } from '@playwright/test';
import { setupMocks, setupSefariaOriginFixture, waitForPanelReady, sendMessage } from './helpers.js';

test('location pin renders via tref fallback when /api/ref 404s', async ({ page }) => {
  const consoleErrors = [];
  page.on('console', (msg) => {
    if (msg.type() === 'error') consoleErrors.push(msg.text());
  });

  await setupSefariaOriginFixture(page);
  // mock404Ref=true: GET https://www.sefaria.org/api/ref/** → 404
  await setupMocks(page, { mock404Ref: true });

  await page.goto('https://www.sefaria.org/Genesis.1.1');
  await waitForPanelReady(page);

  await sendMessage(page, 'What does this text mean?');

  // Wait for the user message to be sent (status goes from 'sending' to 'sent')
  // The location tag appears on .message.user elements
  await page.waitForSelector('.message.user', { timeout: 10_000 });

  // LocationTag renders <a class="lc-location-tag"> inside .message-location-tag
  const locationTag = page.locator('a.lc-location-tag');
  await expect(locationTag).toBeVisible({ timeout: 10_000 });

  // Assert href
  const href = await locationTag.getAttribute('href');
  expect(href).toBe('https://www.sefaria.org/Genesis.1.1');

  // Assert label text (inside .lc-location-ref > bdi)
  const labelText = await page.locator('.lc-location-ref').innerText();
  expect(labelText).toContain('Genesis');

  if (consoleErrors.length > 0) {
    console.log('[test2 console errors]', consoleErrors);
  }
});
