// Generated by OrchestKit Claude Plugin
// Created: 2026-06-23

/**
 * Test 4 — Final-response scroll positioning
 *
 * Per the latency UX spec, on final response generation the canvas auto-scrolls
 * so the TOP edge of the response package sits ~80px below the canvas top
 * (RESPONSE_PACKAGE_TOP_OFFSET) — it must NOT stay pinned to the bottom.
 *
 * Regression guard: scrollToResponseStart() previously called
 * `querySelectorAll(...).at(-1)` on a NodeList (which has no Array.at) and
 * threw, so the reposition never ran and the view stayed at the bottom.
 *
 * We force a tall response package with a long markdown answer so the package
 * is taller than the viewport and the 80px positioning is observable.
 */

import { test, expect } from '@playwright/test';
import { setupMocks, setupSefariaOriginFixture, waitForPanelReady, sendMessage } from './helpers.js';

const LONG_ANSWER = Array.from({ length: 40 }, (_, i) =>
  `Paragraph ${i + 1}: This is a long answer about Genesis 1:1 used to make the response package taller than the chat viewport so the 80px top-offset scroll positioning is observable.`
).join('\n\n');

test('final response scrolls so the response package top sits ~80px from the canvas top', async ({ page }) => {
  await setupSefariaOriginFixture(page);
  await setupMocks(page, { mock404Ref: false, markdown: LONG_ANSWER });

  await page.goto('https://www.sefaria.org/Genesis.1.1');
  await waitForPanelReady(page);

  await sendMessage(page, 'Tell me a lot about Genesis 1:1');

  await page.waitForSelector('.lc-response-package', { timeout: 15_000 });

  // Let the smooth auto-scroll settle.
  await page.waitForTimeout(1200);

  const metrics = await page.evaluate(() => {
    const sr = document.querySelector('lc-chatbot').shadowRoot;
    const container = sr.querySelector('.lc-chatbot-messages');
    const pkg = [...sr.querySelectorAll('.lc-response-package')].at(-1);
    const cRect = container.getBoundingClientRect();
    const pRect = pkg.getBoundingClientRect();
    return {
      offsetPx: Math.round(pRect.top - cRect.top),
      scrollTop: Math.round(container.scrollTop),
      scrollMax: Math.round(container.scrollHeight - container.clientHeight),
      pkgTallerThanViewport: pRect.height > cRect.height,
      scrollBehavior: getComputedStyle(container).scrollBehavior,
    };
  });

  // The package must be taller than the viewport for this assertion to be meaningful.
  expect(metrics.pkgTallerThanViewport).toBe(true);

  // Top of the response package sits ~80px below the canvas top (allow for rounding/animation).
  expect(metrics.offsetPx).toBeGreaterThanOrEqual(60);
  expect(metrics.offsetPx).toBeLessThanOrEqual(100);

  // It must NOT be pinned to the bottom (the bug symptom).
  expect(metrics.scrollTop).toBeLessThan(metrics.scrollMax - 50);

  // Auto-scroll uses smooth behavior per spec.
  expect(metrics.scrollBehavior).toBe('smooth');
});
