// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

/**
 * Test 1 — Trail ref link
 *
 * When a tool_start event with refData.is_ref=true arrives, the ProgressTrail
 * component renders a clickable <a class="trail-ref-link"> inside the thought
 * accordion. This test verifies: href, text content, and target="_blank".
 *
 * Origin: sefaria.org (same fixture used by all three tests).
 * The thought accordion is collapsed by default; we expand it to find the link.
 */

import { test, expect } from '@playwright/test';
import { setupMocks, setupSefariaOriginFixture, waitForPanelReady, sendMessage } from './helpers.js';

test('trail ref link renders with correct href and target', async ({ page }) => {
  // Collect console errors for diagnostics
  const consoleErrors = [];
  page.on('console', (msg) => {
    if (msg.type() === 'error') consoleErrors.push(msg.text());
  });

  await setupSefariaOriginFixture(page);
  await setupMocks(page, { mock404Ref: false });

  await page.goto('https://www.sefaria.org/Genesis.1.1');
  await waitForPanelReady(page);

  await sendMessage(page, 'Tell me about Genesis 1:1');

  // Wait for the assistant response package to appear
  await page.waitForSelector('.lc-response-package', { timeout: 15_000 });

  // The trail ref link lives inside the thought accordion.
  // The accordion toggle button is rendered by Accordion.svelte; click it to expand.
  // The accordion for "thought" is the one that wraps ProgressTrail.
  // We look for the trail-ref-link directly — if the accordion starts open or
  // Playwright can pierce it, great; otherwise expand the thought accordion first.
  let trailLink = page.locator('a.trail-ref-link');

  // If the link isn't immediately visible, expand the thought accordion
  const isVisible = await trailLink.isVisible().catch(() => false);
  if (!isVisible) {
    // Find accordion toggle button for "thought" — it wraps ProgressTrail
    // The Accordion component renders a <button> with class lc-accordion-toggle or similar
    // Try clicking a button inside lc-response-package that isn't the feedback buttons
    const accordionToggles = page.locator('.lc-response-package button');
    const count = await accordionToggles.count();
    for (let i = 0; i < count; i++) {
      await accordionToggles.nth(i).click();
      const nowVisible = await trailLink.isVisible().catch(() => false);
      if (nowVisible) break;
    }
  }

  await expect(trailLink).toBeVisible({ timeout: 8_000 });

  // Assert href
  const href = await trailLink.getAttribute('href');
  expect(href).toBe('https://www.sefaria.org/Genesis.1.1');

  // Assert text contains the English ref label
  const text = await trailLink.innerText();
  expect(text).toContain('Genesis 1:1');

  // Assert opens in new tab
  const target = await trailLink.getAttribute('target');
  expect(target).toBe('_blank');

  if (consoleErrors.length > 0) {
    console.log('[test1 console errors]', consoleErrors);
  }
});
