// Generated by OrchestKit Claude Plugin
// Created: 2026-06-23

/**
 * Test 5 — Trail ref link, client-side fallback
 *
 * The ref API replaced the client-side trail-link logic. To ensure that feature
 * doesn't break when the backend can't attach refData (e.g. /api/ref unavailable,
 * backend unreachable, or a non-ref-bearing tool), ProgressTrail falls back to
 * linkifying quoted refs in the tool description itself.
 *
 * Here the mocked tool_start carries NO refData; the link must still render.
 */

import { test, expect } from '@playwright/test';
import { setupMocks, setupSefariaOriginFixture, waitForPanelReady, sendMessage } from './helpers.js';

test('trail ref link renders via client-side fallback when backend sends no refData', async ({ page }) => {
  await setupSefariaOriginFixture(page);
  await setupMocks(page, { omitRefData: true });

  await page.goto('https://www.sefaria.org/Genesis.1.1');
  await waitForPanelReady(page);

  await sendMessage(page, 'Tell me about Genesis 1:1');
  await page.waitForSelector('.lc-response-package', { timeout: 15_000 });

  let trailLink = page.locator('a.trail-ref-link');
  const isVisible = await trailLink.isVisible().catch(() => false);
  if (!isVisible) {
    const toggles = page.locator('.lc-response-package button');
    const count = await toggles.count();
    for (let i = 0; i < count; i++) {
      await toggles.nth(i).click();
      if (await trailLink.isVisible().catch(() => false)) break;
    }
  }

  await expect(trailLink).toBeVisible({ timeout: 8_000 });

  // Fallback derives the URL + label from the quoted ref in the description.
  expect(await trailLink.getAttribute('href')).toBe('https://www.sefaria.org/Genesis.1.1');
  expect(await trailLink.innerText()).toContain('Genesis 1:1');
  expect(await trailLink.getAttribute('target')).toBe('_blank');
});
