# Generated by Django 4.2.27 on 2026-01-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('page_url', models.URLField(blank=True, default='', max_length=2000)),
                ('locale', models.CharField(blank=True, default='', max_length=10)),
                ('client_version', models.CharField(blank=True, default='', max_length=20)),
                ('response_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_message', to='chat.chatmessage')),
            ],
            options={
                'ordering': ['server_timestamp'],
                'indexes': [models.Index(fields=['session_id', 'server_timestamp'], name='chat_chatme_session_5f9d4e_idx'), models.Index(fields=['user_id', 'server_timestamp'], name='chat_chatme_user_id_64ed86_idx')],
            },
        ),
    ]
