# Generated by Django 4.2.27 on 2026-01-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_cache_creation_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BraintrustLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('turn_id', models.CharField(db_index=True, max_length=100)),
                ('decision_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_message', models.TextField()),
                ('conversation_summary', models.TextField(blank=True, default='')),
                ('flow', models.CharField(blank=True, default='', max_length=20)),
                ('core_prompt_id', models.CharField(blank=True, default='', max_length=100)),
                ('core_prompt_version', models.CharField(blank=True, default='', max_length=50)),
                ('flow_prompt_id', models.CharField(blank=True, default='', max_length=100)),
                ('flow_prompt_version', models.CharField(blank=True, default='', max_length=50)),
                ('tools_available', models.JSONField(default=list)),
                ('tools_used', models.JSONField(default=list)),
                ('assistant_response', models.TextField(blank=True, default='')),
                ('was_refused', models.BooleanField(default=False)),
                ('refusal_reason_codes', models.JSONField(default=list)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('llm_calls', models.IntegerField(blank=True, null=True)),
                ('tool_calls_count', models.IntegerField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.FloatField(blank=True, null=True)),
                ('environment', models.CharField(default='dev', max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('braintrust_input', models.JSONField(blank=True, help_text='Full input payload for Braintrust', null=True)),
                ('braintrust_output', models.JSONField(blank=True, help_text='Full output payload for Braintrust', null=True)),
                ('braintrust_metadata', models.JSONField(blank=True, help_text='Additional metadata for Braintrust', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('turn_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_message', models.TextField()),
                ('conversation_summary_used', models.TextField(blank=True, default='')),
                ('previous_flow', models.CharField(blank=True, default='', max_length=20)),
                ('flow', models.CharField(choices=[('HALACHIC', 'Halachic'), ('GENERAL', 'General Learning'), ('SEARCH', 'Search'), ('REFUSE', 'Refuse/Guardrail')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason_codes', models.JSONField(default=list, help_text='List of reason codes for the decision')),
                ('core_prompt_id', models.CharField(blank=True, default='', max_length=100)),
                ('core_prompt_version', models.CharField(blank=True, default='', max_length=50)),
                ('flow_prompt_id', models.CharField(blank=True, default='', max_length=100)),
                ('flow_prompt_version', models.CharField(blank=True, default='', max_length=50)),
                ('tools_attached', models.JSONField(default=list, help_text='List of tool names attached for this turn')),
                ('session_action', models.CharField(choices=[('CONTINUE', 'Continue'), ('SWITCH_FLOW', 'Switch Flow'), ('END', 'End')], default='CONTINUE', max_length=20)),
                ('safety_allowed', models.BooleanField(default=True)),
                ('refusal_message', models.TextField(blank=True, default='')),
                ('guardrail_triggered', models.JSONField(default=list, help_text='List of guardrails triggered')),
                ('router_latency_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('turn_id', models.CharField(db_index=True, max_length=100)),
                ('decision_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('langsmith_run_id', models.CharField(blank=True, default='', max_length=100)),
                ('langsmith_span_id', models.CharField(blank=True, default='', max_length=100)),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('tool_input', models.JSONField(help_text='Validated tool arguments')),
                ('tool_output', models.JSONField(blank=True, help_text='Tool result', null=True)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_type', models.CharField(blank=True, default='', max_length=100)),
                ('flow', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['start_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='flow',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='turn_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='conversation_summary',
            field=models.TextField(blank=True, default='', help_text='Rolling summary of conversation for router context'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_flow',
            field=models.CharField(blank=True, default='', help_text='Current conversation flow (HALACHIC, GENERAL, SEARCH)', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='turn_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_locale',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('refused', 'Refused')], default='success', max_length=10),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['turn_id'], name='chat_chatme_turn_id_32dc08_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcallevent',
            index=models.Index(fields=['session_id', 'start_timestamp'], name='chat_toolca_session_6ef2de_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcallevent',
            index=models.Index(fields=['tool_name', 'start_timestamp'], name='chat_toolca_tool_na_8eb7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcallevent',
            index=models.Index(fields=['turn_id'], name='chat_toolca_turn_id_e4866b_idx'),
        ),
        migrations.AddIndex(
            model_name='routedecision',
            index=models.Index(fields=['session_id', 'created_at'], name='chat_routed_session_5c6586_idx'),
        ),
        migrations.AddIndex(
            model_name='routedecision',
            index=models.Index(fields=['flow', 'created_at'], name='chat_routed_flow_d854f1_idx'),
        ),
        migrations.AddIndex(
            model_name='braintrustlog',
            index=models.Index(fields=['session_id', 'created_at'], name='chat_braint_session_3f84e3_idx'),
        ),
        migrations.AddIndex(
            model_name='braintrustlog',
            index=models.Index(fields=['flow', 'created_at'], name='chat_braint_flow_10f10e_idx'),
        ),
        migrations.AddIndex(
            model_name='braintrustlog',
            index=models.Index(fields=['environment', 'created_at'], name='chat_braint_environ_dad02c_idx'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='route_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.routedecision'),
        ),
    ]
