# Generated by ChatGPT on 2026-01-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_unused_logging_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("current_topic", models.CharField(blank=True, default="", max_length=255)),
                ("user_intent", models.CharField(blank=True, default="", max_length=100)),
                ("flow", models.CharField(blank=True, default="", max_length=20)),
                ("texts_referenced", models.JSONField(default=list)),
                ("topics_discussed", models.JSONField(default=list)),
                ("people_mentioned", models.JSONField(default=list)),
                ("halachic_domain", models.CharField(blank=True, default="", max_length=100)),
                ("constraints", models.JSONField(default=list)),
                ("safety_flags", models.JSONField(default=list)),
                ("turn_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_updated", "-created_at"],
            },
        ),
    ]
