# Generated by Django 4.2.27 on 2026-02-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_conversation_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="cost_usd",
            field=models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True),
        ),
    ]
