# Generated by Django 4.2.27 on 2026-03-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_alter_chatsession_conversation_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="processing_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="processing_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="processing_heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="processing_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("started", "Started"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
