# Generated by Django 4.2.27 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_chatmessage_processing_heartbeat"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE chat_chatsession "
                    "ADD COLUMN IF NOT EXISTS title varchar(64) NOT NULL DEFAULT '';"
                ),
                migrations.RunSQL(
                    "ALTER TABLE chat_chatsession "
                    "ADD COLUMN IF NOT EXISTS title_updated_at timestamptz NULL;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE chat_chatsession "
                    "ADD COLUMN IF NOT EXISTS is_deleted boolean NOT NULL DEFAULT false;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE chat_chatsession "
                    "ADD COLUMN IF NOT EXISTS deleted_at timestamptz NULL;"
                ),
                migrations.RunSQL(
                    "CREATE INDEX IF NOT EXISTS chat_chatsession_is_deleted_80fe5a75 "
                    "ON chat_chatsession (is_deleted);"
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="chatsession",
                    name="title",
                    field=models.CharField(blank=True, default="", max_length=64),
                ),
                migrations.AddField(
                    model_name="chatsession",
                    name="title_updated_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="chatsession",
                    name="is_deleted",
                    field=models.BooleanField(db_index=True, default=False),
                ),
                migrations.AddField(
                    model_name="chatsession",
                    name="deleted_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]
