# Generated by Django 4.2.30 on 2026-09-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_hash_numeric_user_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="processing_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("started", "Started"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
