# Generated by Django 4.2.27 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_saved_conversation_metadata"),
        ("chat", "0011_hash_numeric_user_ids"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE chat_chatmessage "
                    "ADD COLUMN IF NOT EXISTS appetizer_data jsonb NULL;"
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="chatmessage",
                    name="appetizer_data",
                    field=models.JSONField(
                        blank=True,
                        help_text="Prompt-level topic appetizer metadata displayed in chat history",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS chat_chatsession_title_fts_idx
                ON chat_chatsession
                USING GIN (to_tsvector('simple', coalesce(title, '')));
            """,
            reverse_sql="DROP INDEX IF EXISTS chat_chatsession_title_fts_idx;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS chat_chatmessage_content_fts_idx
                ON chat_chatmessage
                USING GIN (to_tsvector('simple', coalesce(content, '')));
            """,
            reverse_sql="DROP INDEX IF EXISTS chat_chatmessage_content_fts_idx;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS chat_chatmessage_appetizer_fts_idx
                ON chat_chatmessage
                USING GIN (to_tsvector('simple', coalesce(appetizer_data::text, '')));
            """,
            reverse_sql="DROP INDEX IF EXISTS chat_chatmessage_appetizer_fts_idx;",
        ),
    ]
