# Generated by Django 4.2.30 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_appetizer_data_and_history_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="counts_toward_anon_limit",
            field=models.BooleanField(default=True),
        ),
    ]
