# Generated by Django 4.2.28 on 2026-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_appetizer_data_and_history_search_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="processing_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("started", "Started"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelling", "Cancelling"),
                    ("cancelled", "Cancelled"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
