# Generated by OrchestKit Claude Plugin
# Created: 2026-02-17

"""Tests for load-testing routing: get_agent_service factory, get_braintrust_config,
and the _setup_braintrust_tracing early-return path.

Coverage targets:
- get_agent_service(is_load_testing=True) routes to MOCK_ANTHROPIC_URL
- get_agent_service(is_load_testing=False) creates a plain service
- get_braintrust_config() returns enabled=True by default
- get_braintrust_config() returns enabled=False when BRAINTRUST_LOGGING_ENABLED=false
- _setup_braintrust_tracing returns early (no SDK setup) when logging is disabled
"""

from __future__ import annotations

from unittest.mock import MagicMock, call, patch

import pytest


# ---------------------------------------------------------------------------
# get_braintrust_config
# ---------------------------------------------------------------------------


class TestGetBraintrustConfig:
    """get_braintrust_config reads environment variables and exposes an 'enabled' flag."""

    def test_enabled_defaults_to_true_when_env_unset(self):
        """BRAINTRUST_LOGGING_ENABLED absent → enabled=True."""
        with patch.dict("os.environ", {}, clear=False):
            # Remove the key if it happens to be present in the test environment
            import os

            os.environ.pop("BRAINTRUST_LOGGING_ENABLED", None)

            from chat.V2.utils import get_braintrust_config

            config = get_braintrust_config()

        assert config.enabled is True

    def test_enabled_is_true_when_set_to_true(self):
        """BRAINTRUST_LOGGING_ENABLED=true → enabled=True."""
        with patch.dict("os.environ", {"BRAINTRUST_LOGGING_ENABLED": "true"}):
            from chat.V2.utils import get_braintrust_config

            config = get_braintrust_config()

        assert config.enabled is True

    @pytest.mark.parametrize("value", ["false", "False", "FALSE"])
    def test_enabled_is_false_when_set_to_false(self, value):
        """BRAINTRUST_LOGGING_ENABLED=false (any case) → enabled=False."""
        with patch.dict("os.environ", {"BRAINTRUST_LOGGING_ENABLED": value}):
            from chat.V2.utils import get_braintrust_config

            config = get_braintrust_config()

        assert config.enabled is False

    def test_api_key_and_project_are_read_from_env(self):
        """api_key and project fields are populated from environment variables."""
        env = {
            "BRAINTRUST_API_KEY": "test-bt-key-xyz",
            "BRAINTRUST_PROJECT": "MyProject",
            "BRAINTRUST_LOGGING_ENABLED": "true",
        }
        with patch.dict("os.environ", env):
            from chat.V2.utils import get_braintrust_config

            config = get_braintrust_config()

        assert config.api_key == "test-bt-key-xyz"
        assert config.project == "MyProject"

    def test_project_defaults_when_env_unset(self):
        """BRAINTRUST_PROJECT absent → falls back to 'On Site Agent'."""
        import os

        with patch.dict("os.environ", {}, clear=False):
            os.environ.pop("BRAINTRUST_PROJECT", None)

            from chat.V2.utils import get_braintrust_config

            config = get_braintrust_config()

        assert config.project == "On Site Agent"


# ---------------------------------------------------------------------------
# get_agent_service factory
# ---------------------------------------------------------------------------


class TestGetAgentServiceFactory:
    """get_agent_service(is_load_testing) should route to mock server or real API."""

    def _make_mock_service_cls(self):
        """Return a MagicMock that tracks __init__ kwargs."""
        mock_cls = MagicMock()
        mock_cls.return_value = MagicMock()
        return mock_cls

    def test_load_test_false_creates_plain_service(self):
        """is_load_testing=False → ClaudeAgentService() called without base_url."""
        with patch("chat.V2.agent.claude_service.ClaudeAgentService") as mock_cls:
            mock_cls.return_value = MagicMock()
            from chat.V2.agent.claude_service import get_agent_service

            get_agent_service(is_load_testing=False)

        mock_cls.assert_called_once_with()

    def test_load_test_true_creates_service_with_mock_url(self):
        """is_load_testing=True → ClaudeAgentService(base_url=_MOCK_ANTHROPIC_URL).

        The module-level constant _MOCK_ANTHROPIC_URL is set at import time, so
        we patch it directly on the module rather than reloading the module.
        """
        import chat.V2.agent.claude_service as svc_module

        sentinel_url = "http://mock-sentinel:8002"
        with patch.object(svc_module, "_MOCK_ANTHROPIC_URL", sentinel_url):
            with patch.object(svc_module, "ClaudeAgentService") as mock_cls:
                mock_cls.return_value = MagicMock()
                svc_module.get_agent_service(is_load_testing=True)

        mock_cls.assert_called_once_with(base_url=sentinel_url)

    def test_default_argument_is_not_load_testing(self):
        """get_agent_service() with no arguments defaults to is_load_testing=False."""
        with patch("chat.V2.agent.claude_service.ClaudeAgentService") as mock_cls:
            mock_cls.return_value = MagicMock()
            from chat.V2.agent.claude_service import get_agent_service

            get_agent_service()  # no arg

        mock_cls.assert_called_once_with()

    def test_mock_anthropic_url_constant_used_as_base_url(self):
        """_MOCK_ANTHROPIC_URL constant is passed as base_url when load testing.

        The default value comes from the environment at import time. We patch
        the module-level constant directly to verify routing behaviour without
        reloading the module.
        """
        import chat.V2.agent.claude_service as svc_module

        custom_url = "http://my-custom-mock:9999"
        with patch.object(svc_module, "_MOCK_ANTHROPIC_URL", custom_url):
            with patch.object(svc_module, "ClaudeAgentService") as mock_cls:
                mock_cls.return_value = MagicMock()
                svc_module.get_agent_service(is_load_testing=True)

        mock_cls.assert_called_once_with(base_url=custom_url)


# ---------------------------------------------------------------------------
# _setup_braintrust_tracing early return
# ---------------------------------------------------------------------------


class TestSetupBraintrustTracingDisabled:
    """When Braintrust logging is disabled, _setup_braintrust_tracing is a no-op."""

    def test_no_sdk_setup_when_logging_disabled(self):
        """setup_claude_agent_sdk must NOT be called when braintrust_logging_enabled=False."""
        mock_setup = MagicMock()

        with patch.dict(
            "os.environ",
            {
                "BRAINTRUST_API_KEY": "key",
                "BRAINTRUST_LOGGING_ENABLED": "false",
                "ANTHROPIC_API_KEY": "ant-key",
            },
        ):
            with patch(
                "chat.V2.agent.claude_service.setup_claude_agent_sdk", mock_setup
            ):
                from chat.V2.agent import claude_service

                # Reset so a fresh instance triggers setup path
                claude_service._BRAINTRUST_SETUP_DONE = False

                with (
                    patch.object(claude_service, "ClaudeAgentOptions", MagicMock()),
                    patch.object(claude_service, "ClaudeSDKClient", MagicMock()),
                    patch.object(claude_service, "create_sdk_mcp_server", MagicMock()),
                    patch.object(claude_service, "tool", MagicMock()),
                ):
                    try:
                        service = claude_service.ClaudeAgentService()
                        assert service.braintrust_logging_enabled is False
                    except RuntimeError:
                        pytest.skip("claude-agent-sdk not installed")

        mock_setup.assert_not_called()

    def test_braintrust_logging_enabled_flag_set_on_service(self):
        """ClaudeAgentService.braintrust_logging_enabled reflects the config."""
        with patch.dict(
            "os.environ",
            {
                "BRAINTRUST_API_KEY": "key",
                "BRAINTRUST_LOGGING_ENABLED": "false",
                "ANTHROPIC_API_KEY": "ant-key",
            },
        ):
            with patch("chat.V2.agent.claude_service.setup_claude_agent_sdk"):
                from chat.V2.agent import claude_service

                claude_service._BRAINTRUST_SETUP_DONE = False

                with (
                    patch.object(claude_service, "ClaudeAgentOptions", MagicMock()),
                    patch.object(claude_service, "ClaudeSDKClient", MagicMock()),
                    patch.object(claude_service, "create_sdk_mcp_server", MagicMock()),
                    patch.object(claude_service, "tool", MagicMock()),
                ):
                    try:
                        service = claude_service.ClaudeAgentService()
                    except RuntimeError:
                        pytest.skip("claude-agent-sdk not installed")

                assert service.braintrust_logging_enabled is False
