services:
  weblate:
    image: weblate/weblate:5.17.1.0
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
    volumes:
      - 'weblate-data:/app/data'
    environment:
      WEBLATE_SITE_DOMAIN: '${WEBLATE_SITE_DOMAIN}'
      WEBLATE_SITE_TITLE: '${WEBLATE_SITE_TITLE}'
      WEBLATE_ADMIN_EMAIL: '${WEBLATE_ADMIN_EMAIL}'
      WEBLATE_ADMIN_NAME: '${WEBLATE_ADMIN_NAME}'
      WEBLATE_ADMIN_PASSWORD: '${WEBLATE_ADMIN_PASSWORD}'
      WEBLATE_SECRET_KEY: '${WEBLATE_SECRET_KEY}'
      WEBLATE_ALLOWED_HOSTS: '${WEBLATE_ALLOWED_HOSTS}'
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: weblate
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      WEBLATE_REGISTRATION_OPEN: '${WEBLATE_REGISTRATION_OPEN}'
      WEBLATE_REGISTRATION_ALLOW_BACKENDS: '${WEBLATE_REGISTRATION_ALLOW_BACKENDS}'
      WEBLATE_REQUIRE_LOGIN: '${WEBLATE_REQUIRE_LOGIN}'
      WEBLATE_AUTH_LOCK_DEFAULT: '${WEBLATE_AUTH_LOCK_DEFAULT}'
      WEBLATE_NO_EMAIL_AUTH: '${WEBLATE_NO_EMAIL_AUTH}'
      WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: '${WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY}'
      WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: '${WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET}'
      WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS: '${WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS}'
      WEBLATE_GITHUB_USERNAME: '${WEBLATE_GITHUB_USERNAME}'
      WEBLATE_GITHUB_TOKEN: '${WEBLATE_GITHUB_TOKEN}'
      WEBLATE_GITHUB_HOST: api.github.com
      WEBLATE_GITHUB_WEBHOOK_SECRET: '${WEBLATE_GITHUB_WEBHOOK_SECRET}'
      WEBLATE_ENABLE_HTTPS: '${WEBLATE_ENABLE_HTTPS}'
      WEBLATE_IP_PROXY_HEADER: '${WEBLATE_IP_PROXY_HEADER}'
      WEBLATE_SECURE_PROXY_SSL_HEADER: '${WEBLATE_SECURE_PROXY_SSL_HEADER}'
  database:
    image: 'postgres:15-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_DB: weblate
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - 'weblate-pg-reset2:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'PGPASSWORD="$${POSTGRES_PASSWORD}" psql -h 127.0.0.1 -U weblate -d weblate -c ''SELECT 1'' >/dev/null'
      interval: 5s
      timeout: 5s
      retries: 10
  cache:
    image: 'redis:7-alpine'
    restart: unless-stopped
    command:
      - redis-server
      - '--save'
      - '60'
      - '1'
      - '--requirepass'
      - '${REDIS_PASSWORD}'
    volumes:
      - 'weblate-redis:/data'
volumes:
  weblate-data: null
  weblate-pg-reset2: null
  weblate-redis: null
